# Generated by Django 6.1.1 on 2026-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CANDIDATE_SYNC', 'Candidate Sync'), ('ASSESSMENT_CREATE', 'Assessment Create'), ('RESULT_CALLBACK', 'Result Callback')], db_index=True, max_length=50)),
                ('human_db_user_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('assessment_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('response_status', models.PositiveIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='integration_action_2b277e_idx'), models.Index(fields=['human_db_user_id', 'created_at'], name='integration_human_d_aa4914_idx')],
            },
        ),
    ]
