# Generated by Django 6.1 on 2026-08-21 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=12)),
                ('candidate_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ATTENDED', 'Attended'), ('NOT_ATTENDED', 'Not Attended')], db_index=True, default='NOT_STARTED', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_assigned', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('LOGICAL', 'Logical Reasoning'), ('QUANTITATIVE', 'Quantitative Aptitude'), ('TECHNICAL', 'Technical Aptitude')], db_index=True, max_length=20)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='EASY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section', 'id'],
                'indexes': [models.Index(fields=['section', 'difficulty'], name='assessments_section_6fe2d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', 'candidate_status'], name='assessments_status_9a08a9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['expire_time'], name='assessments_expire__e31bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['employer', 'candidate'], name='assessments_employe_238370_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('expire_time__gt', models.F('start_time'))), name='assessment_expire_after_start'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='assessment_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='unique_question_per_assessment'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_correct'], name='assessments_is_corr_25c8db_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='unique_answer_per_assessment_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.CheckConstraint(condition=models.Q(('selected_answer__in', ('A', 'B', 'C', 'D'))), name='answer_is_valid_option'),
        ),
    ]
