# Generated by Django 6.1 on 2026-08-22 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_seed_initial_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed problem statement')),
                ('input_format', models.TextField(help_text='Expected input format')),
                ('output_format', models.TextField(help_text='Expected output format')),
                ('constraints', models.TextField(blank=True, default='', help_text='Input size & performance constraints')),
                ('sample_input', models.TextField(help_text='Sample input for display')),
                ('sample_output', models.TextField(help_text='Sample expected output for display')),
                ('explanation', models.TextField(blank=True, default='', help_text='Explanation of the sample test cases')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('starter_code', models.JSONField(default=dict, help_text="Dictionary of starter code by language: {'python': '...', 'java': '...', 'cpp': '...', 'javascript': '...'}")),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='has_coding',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False, help_text='True if this is a sample visible test case; False if hidden evaluator test case.')),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assessments.codingquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentCodingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_questions', to='assessments.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignments', to='assessments.codingquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='unique_coding_question_per_assessment')],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('java', 'Java'), ('cpp', 'C++'), ('javascript', 'JavaScript')], default='python', max_length=20)),
                ('source_code', models.TextField(blank=True, default='')),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_submitted', models.BooleanField(default=False)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='assessments.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.codingquestion')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'question'), name='unique_submission_per_assessment_coding_question')],
            },
        ),
    ]
