# Generated by Django 6.1 on 2026-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_codingquestion_assessment_has_coding_codingtestcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='category',
            field=models.CharField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('hashing', 'Hashing'), ('two_pointers', 'Two Pointers / Sliding Window'), ('search_sort', 'Searching / Sorting'), ('stack_queue', 'Stack / Queue'), ('linked_list', 'Linked List'), ('recursion', 'Recursion'), ('trees', 'Trees'), ('dp', 'Dynamic Programming')], default='arrays', help_text='Primary algorithmic domain or data structure category', max_length=30),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='starter_code',
            field=models.JSONField(default=dict, help_text="Dictionary of starter scaffold comments by language: {'python': '...', 'java': '...', 'cpp': '...', 'javascript': '...'}"),
        ),
    ]
