# Generated by Django 6.1 on 2026-08-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_codingquestion_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='auto_submitted_for_malpractice',
            field=models.BooleanField(default=False, help_text='Flag indicating if the assessment was terminated and auto-submitted for malpractice'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_violation_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent violation', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='last_violation_type',
            field=models.CharField(blank=True, default='', help_text='Type of the last recorded violation (e.g. FULLSCREEN_EXIT, DEVTOOLS_SHORTCUT, TAB_SWITCH)', max_length=100),
        ),
        migrations.AddField(
            model_name='assessment',
            name='malpractice_status',
            field=models.BooleanField(default=False, help_text='Flag indicating if the candidate exceeded the maximum allowed violations'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_violations',
            field=models.PositiveIntegerField(default=3, help_text='Maximum allowed violations before automatic submission'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='violation_count',
            field=models.PositiveIntegerField(default=0, help_text='Count of proctoring violations recorded during the assessment'),
        ),
    ]
