# Generated by Django 6.1 on 2026-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_assessment_auto_submitted_for_malpractice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='submission_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for assessment submission (e.g. standard completion, auto-submitted for malpractice)', max_length=255),
        ),
    ]
