# Generated by Django 6.1 on 2026-08-23 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_submission_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent AI assessment analysis', null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ai_reasoning',
            field=models.TextField(blank=True, default='', help_text='Legitimate data-backed explanation for the AI recommendation'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='ai_recommendation',
            field=models.CharField(blank=True, choices=[('STRONG_MATCH', 'Strong Match'), ('REVIEW_RECOMMENDED', 'Review Recommended'), ('LOW_MATCH', 'Low Match'), ('PENDING', 'Pending Analysis')], default='', help_text='AI decision support recommendation: STRONG_MATCH, REVIEW_RECOMMENDED, LOW_MATCH', max_length=50),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_shortlisted',
            field=models.BooleanField(db_index=True, default=False, help_text='Employer final shortlist status'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shortlist_notes',
            field=models.TextField(blank=True, default='', help_text='Optional recruiter notes or feedback on shortlisting'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the candidate was shortlisted by the employer', null=True),
        ),
        migrations.CreateModel(
            name='AssessmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('has_coding', models.BooleanField(default=False)),
                ('total_mcq_count', models.PositiveIntegerField(default=0)),
                ('total_coding_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional campaign/batch group if part of a multi-candidate assessment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.assessmentgroup'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['group', 'status'], name='assessments_group_i_651f54_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_shortlisted'], name='assessments_is_shor_3ef9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['ai_recommendation'], name='assessments_ai_reco_74ee93_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('group', 'candidate'), name='unique_candidate_per_assessment_group'),
        ),
        migrations.AddIndex(
            model_name='assessmentgroup',
            index=models.Index(fields=['employer', 'created_at'], name='assessments_employe_374d93_idx'),
        ),
    ]
