# Generated by Django 6.1 on 2026-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_ai_analyzed_at_assessment_ai_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestion',
            name='ai_provider',
            field=models.CharField(blank=True, default='', help_text='AI provider/model name if AI generated', max_length=100),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status for safe soft-deactivation'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether challenge is approved for tests'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='is_reviewed',
            field=models.BooleanField(default=True, help_text='Whether challenge has been reviewed'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='memory_limit_mb',
            field=models.PositiveIntegerField(default=256, help_text='Memory ceiling in megabytes'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='source_type',
            field=models.CharField(choices=[('ADMIN_CREATED', 'Admin Created'), ('CURATED', 'Curated'), ('IMPORTED', 'Imported'), ('AI_GENERATED', 'AI Generated')], db_index=True, default='CURATED', max_length=20),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(default=5, help_text='Execution timeout limit in seconds'),
        ),
        migrations.AddField(
            model_name='question',
            name='ai_provider',
            field=models.CharField(blank=True, default='', help_text='AI provider/model name if AI generated', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Topic or subcategory', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation for the correct answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active status for safe soft-deactivation'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Whether question is approved for tests'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_reviewed',
            field=models.BooleanField(default=True, help_text='Whether question has been reviewed'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('ADMIN_CREATED', 'Admin Created'), ('CURATED', 'Curated'), ('IMPORTED', 'Imported'), ('AI_GENERATED', 'AI Generated')], db_index=True, default='CURATED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='codingquestion',
            index=models.Index(fields=['category', 'difficulty'], name='assessments_categor_5c991f_idx'),
        ),
        migrations.AddIndex(
            model_name='codingquestion',
            index=models.Index(fields=['source_type', 'is_active'], name='assessments_source__9dcd27_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['source_type', 'is_active'], name='assessments_source__28f5c2_idx'),
        ),
    ]
