# Generated by Django 6.1.1 on 2026-09-18 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_codingquestion_ai_provider_codingquestion_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='question_source',
            field=models.CharField(choices=[('BANK', 'Question Bank'), ('DOCUMENT', 'Uploaded Document')], db_index=True, default='BANK', help_text='Source of questions: global question bank or uploaded document', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='question_source',
            field=models.CharField(choices=[('BANK', 'Question Bank'), ('DOCUMENT', 'Uploaded Document')], db_index=True, default='BANK', help_text='Source of questions: global question bank or uploaded document', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='document_question_num',
            field=models.PositiveIntegerField(blank=True, help_text='Question number in source document', null=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='source_type',
            field=models.CharField(choices=[('ADMIN_CREATED', 'Admin Created'), ('CURATED', 'Curated'), ('IMPORTED', 'Imported'), ('AI_GENERATED', 'AI Generated'), ('DOCUMENT', 'Uploaded Document')], db_index=True, default='CURATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_type',
            field=models.CharField(choices=[('ADMIN_CREATED', 'Admin Created'), ('CURATED', 'Curated'), ('IMPORTED', 'Imported'), ('AI_GENERATED', 'AI Generated'), ('DOCUMENT', 'Uploaded Document')], db_index=True, default='CURATED', max_length=20),
        ),
        migrations.CreateModel(
            name='AssessmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded question document file (PDF, DOCX, TXT)', upload_to='assessment_documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='File extension / format (pdf, docx, txt)', max_length=10)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('raw_text', models.TextField(blank=True, default='', help_text='Extracted raw text content from the document')),
                ('extracted_count', models.PositiveIntegerField(default=0, help_text='Number of questions extracted')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_assessment_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Source document if created from an uploaded question document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.assessmentdocument'),
        ),
        migrations.AddField(
            model_name='assessmentgroup',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Source document if created from an uploaded question document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_groups', to='assessments.assessmentdocument'),
        ),
        migrations.AddField(
            model_name='codingquestion',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Source document if extracted from an uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_coding_questions', to='assessments.assessmentdocument'),
        ),
        migrations.AddField(
            model_name='question',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text='Source document if extracted from an uploaded document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_questions', to='assessments.assessmentdocument'),
        ),
    ]
