"""Curated Coding Problems repository and seeder.

Comprehensive bank of 52 high-quality DSA interview problems organized across 10 domains:
- Arrays (10)
- Strings (8)
- Hashing (5)
- Two Pointers / Sliding Window (5)
- Searching / Sorting (5)
- Stack / Queue (5)
- Linked List (4)
- Recursion (3)
- Trees (3)
- Dynamic Programming (4)

SECURITY & INTEGRITY RULES:
- All starter code contains minimal comment scaffolds ONLY (no solutions).
- Reference algorithms and solutions remain strictly server-side.
- Hidden test cases are never sent to candidate frontend contexts.
"""

import logging
from typing import Any, Dict, List
from assessments.models import CodingQuestion, CodingTestCase

logger = logging.getLogger(__name__)

EMPTY_STARTER_CODE: Dict[str, str] = {
    "python": "# Write your solution here\n",
    "java": "// Write your solution here\n",
    "cpp": "// Write your solution here\n",
    "javascript": "// Write your solution here\n",
}

DEFAULT_CODING_QUESTIONS: List[Dict[str, Any]] = [
    # =========================================================================
    # 1. ARRAYS (10 Questions)
    # =========================================================================
    {
        "title": "Maximum Subarray Sum (Kadane's Algorithm)",
        "slug": "maximum-subarray-sum",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an integer array `nums`, find the subarray with the largest sum, and return its sum.\nA subarray is a contiguous non-empty sequence of elements within an array.",
        "input_format": "A single line of space-separated integers representing the array `nums`.",
        "output_format": "Print the maximum subarray sum as a single integer.",
        "constraints": "1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4",
        "sample_input": "-2 1 -3 4 -1 2 1 -5 4",
        "sample_output": "6",
        "explanation": "The subarray [4, -1, 2, 1] has the largest sum 6.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "-2 1 -3 4 -1 2 1 -5 4", "expected_output": "6", "is_sample": True, "order": 1},
            {"input_data": "1", "expected_output": "1", "is_sample": True, "order": 2},
            {"input_data": "5 4 -1 7 8", "expected_output": "23", "is_sample": False, "order": 3},
            {"input_data": "-1 -2 -3 -4", "expected_output": "-1", "is_sample": False, "order": 4},
            {"input_data": "10 -5 20 -10 30 -50 40", "expected_output": "45", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Product of Array Except Self",
        "slug": "product-of-array-except-self",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all the elements of `nums` except `nums[i]`.\nYou must write an algorithm that runs in O(n) time and without using the division operation.",
        "input_format": "A single line containing space-separated integers for `nums`.",
        "output_format": "Space-separated integers representing the product array.",
        "constraints": "2 <= nums.length <= 10^5\n-30 <= nums[i] <= 30\nThe product of any prefix or suffix of `nums` is guaranteed to fit in a 32-bit integer.",
        "sample_input": "1 2 3 4",
        "sample_output": "24 12 8 6",
        "explanation": "For index 0: 2*3*4 = 24. Index 1: 1*3*4 = 12. Index 2: 1*2*4 = 8. Index 3: 1*2*3 = 6.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 3 4", "expected_output": "24 12 8 6", "is_sample": True, "order": 1},
            {"input_data": "-1 1 0 -3 3", "expected_output": "0 0 9 0 0", "is_sample": True, "order": 2},
            {"input_data": "2 3 5", "expected_output": "15 10 6", "is_sample": False, "order": 3},
            {"input_data": "1 1 1 1", "expected_output": "1 1 1 1", "is_sample": False, "order": 4},
            {"input_data": "0 0", "expected_output": "0 0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Majority Element in an Array",
        "slug": "majority-element-array",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an array `nums` of size `n`, return the majority element.\nThe majority element is the element that appears more than ⌊n / 2⌋ times. You may assume that the majority element always exists in the array.",
        "input_format": "A single line containing space-separated integers.",
        "output_format": "Print the majority element integer.",
        "constraints": "1 <= nums.length <= 5 * 10^4\n-10^9 <= nums[i] <= 10^9",
        "sample_input": "3 2 3",
        "sample_output": "3",
        "explanation": "3 appears 2 times, which is > 3/2 = 1.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 2 3", "expected_output": "3", "is_sample": True, "order": 1},
            {"input_data": "2 2 1 1 1 2 2", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "7", "expected_output": "7", "is_sample": False, "order": 3},
            {"input_data": "6 6 6 7 7", "expected_output": "6", "is_sample": False, "order": 4},
            {"input_data": "100 200 100 100 300 100", "expected_output": "100", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Rotate Array by K Positions",
        "slug": "rotate-array-by-k",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an integer array `nums`, rotate the array to the right by `k` steps, where `k` is non-negative.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `k`.",
        "output_format": "Space-separated integers representing the rotated array.",
        "constraints": "1 <= nums.length <= 10^5\n-2^31 <= nums[i] <= 2^31 - 1\n0 <= k <= 10^5",
        "sample_input": "1 2 3 4 5 6 7\n3",
        "sample_output": "5 6 7 1 2 3 4",
        "explanation": "rotate 1 steps to the right: [7,1,2,3,4,5,6]\nrotate 2 steps: [6,7,1,2,3,4,5]\nrotate 3 steps: [5,6,7,1,2,3,4]",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 3 4 5 6 7\n3", "expected_output": "5 6 7 1 2 3 4", "is_sample": True, "order": 1},
            {"input_data": "-1 -100 3 99\n2", "expected_output": "3 99 -1 -100", "is_sample": True, "order": 2},
            {"input_data": "1 2\n0", "expected_output": "1 2", "is_sample": False, "order": 3},
            {"input_data": "1 2 3 4\n4", "expected_output": "1 2 3 4", "is_sample": False, "order": 4},
            {"input_data": "10 20 30\n5", "expected_output": "20 30 10", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Merge Overlapping Intervals",
        "slug": "merge-overlapping-intervals",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an array of intervals where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.",
        "input_format": "A single line containing pairs of space-separated integers representing interval starts and ends: `s1 e1 s2 e2 ...`",
        "output_format": "Space-separated integers representing the merged intervals.",
        "constraints": "1 <= intervals.length <= 10^4\n0 <= start_i <= end_i <= 10^4",
        "sample_input": "1 3 2 6 8 10 15 18",
        "sample_output": "1 6 8 10 15 18",
        "explanation": "Since intervals [1,3] and [2,6] overlap, merge them into [1,6].",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 3 2 6 8 10 15 18", "expected_output": "1 6 8 10 15 18", "is_sample": True, "order": 1},
            {"input_data": "1 4 4 5", "expected_output": "1 5", "is_sample": True, "order": 2},
            {"input_data": "1 4 0 4", "expected_output": "0 4", "is_sample": False, "order": 3},
            {"input_data": "1 4 2 3", "expected_output": "1 4", "is_sample": False, "order": 4},
            {"input_data": "6 8 1 9 2 4", "expected_output": "1 9", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Find Missing Number in Sequence",
        "slug": "find-missing-number-sequence",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an array `nums` containing `n` distinct numbers in the range `[0, n]`, return the only number in the range that is missing from the array.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Print the missing integer.",
        "constraints": "n == nums.length\n1 <= n <= 10^4\n0 <= nums[i] <= n\nAll the numbers of `nums` are unique.",
        "sample_input": "3 0 1",
        "sample_output": "2",
        "explanation": "n = 3 since there are 3 numbers, so all numbers are in the range [0,3]. 2 is the missing number.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 0 1", "expected_output": "2", "is_sample": True, "order": 1},
            {"input_data": "0 1", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "9 6 4 2 3 5 7 0 1", "expected_output": "8", "is_sample": False, "order": 3},
            {"input_data": "1", "expected_output": "0", "is_sample": False, "order": 4},
            {"input_data": "0", "expected_output": "1", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Move Zeroes to End",
        "slug": "move-zeroes-to-end",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Given an integer array `nums`, move all 0's to the end of it while maintaining the relative order of the non-zero elements.\nNote that you must do this in-place without making a copy of the array.",
        "input_format": "A single line containing space-separated integers.",
        "output_format": "Space-separated integers with all zeroes moved to the end.",
        "constraints": "1 <= nums.length <= 10^4\n-2^31 <= nums[i] <= 2^31 - 1",
        "sample_input": "0 1 0 3 12",
        "sample_output": "1 3 12 0 0",
        "explanation": "Non-zero values [1, 3, 12] maintain order, with 0s appended at the end.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "0 1 0 3 12", "expected_output": "1 3 12 0 0", "is_sample": True, "order": 1},
            {"input_data": "0", "expected_output": "0", "is_sample": True, "order": 2},
            {"input_data": "1 2 3", "expected_output": "1 2 3", "is_sample": False, "order": 3},
            {"input_data": "0 0 1", "expected_output": "1 0 0", "is_sample": False, "order": 4},
            {"input_data": "4 0 5 0 6 0", "expected_output": "4 5 6 0 0 0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Best Time to Buy and Sell Stock",
        "slug": "best-time-to-buy-and-sell-stock",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "You are given an array `prices` where `prices[i]` is the price of a given stock on the `i`-th day.\nYou want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.\nReturn the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.",
        "input_format": "A single line containing space-separated integers representing daily stock prices.",
        "output_format": "Print the maximum profit integer.",
        "constraints": "1 <= prices.length <= 10^5\n0 <= prices[i] <= 10^4",
        "sample_input": "7 1 5 3 6 4",
        "sample_output": "5",
        "explanation": "Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "7 1 5 3 6 4", "expected_output": "5", "is_sample": True, "order": 1},
            {"input_data": "7 6 4 3 1", "expected_output": "0", "is_sample": True, "order": 2},
            {"input_data": "1 2 3 4 5", "expected_output": "4", "is_sample": False, "order": 3},
            {"input_data": "2 4 1", "expected_output": "2", "is_sample": False, "order": 4},
            {"input_data": "3 8 1 9", "expected_output": "8", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Container With Most Water",
        "slug": "container-with-most-water",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "You are given an integer array `height` of length `n`. There are `n` vertical lines drawn such that the two endpoints of the `i`-th line are `(i, 0)` and `(i, height[i])`.\nFind two lines that together with the x-axis form a container, such that the container contains the most water.\nReturn the maximum amount of water a container can store.",
        "input_format": "A single line of space-separated integers representing vertical line heights.",
        "output_format": "Print the maximum water area integer.",
        "constraints": "n == height.length\n2 <= n <= 10^5\n0 <= height[i] <= 10^4",
        "sample_input": "1 8 6 2 5 4 8 3 7",
        "sample_output": "49",
        "explanation": "The maximum area is between indices 1 and 8: min(8, 7) * (8 - 1) = 7 * 7 = 49.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 8 6 2 5 4 8 3 7", "expected_output": "49", "is_sample": True, "order": 1},
            {"input_data": "1 1", "expected_output": "1", "is_sample": True, "order": 2},
            {"input_data": "4 3 2 1 4", "expected_output": "16", "is_sample": False, "order": 3},
            {"input_data": "1 2 1", "expected_output": "2", "is_sample": False, "order": 4},
            {"input_data": "2 3 4 5 18 17 6", "expected_output": "17", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Find Minimum in Rotated Sorted Array",
        "slug": "find-minimum-in-rotated-sorted-array",
        "category": CodingQuestion.Categories.ARRAYS,
        "description": "Suppose an array of length `n` sorted in ascending order is rotated between 1 and `n` times.\nGiven the sorted rotated array `nums` of unique elements, return the minimum element of this array.\nYou must write an algorithm that runs in O(log n) time.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Print the minimum element integer.",
        "constraints": "n == nums.length\n1 <= n <= 5000\n-5000 <= nums[i] <= 5000\nAll the integers of `nums` are unique.",
        "sample_input": "3 4 5 1 2",
        "sample_output": "1",
        "explanation": "The original array was [1,2,3,4,5] rotated 3 times. The minimum element is 1.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 4 5 1 2", "expected_output": "1", "is_sample": True, "order": 1},
            {"input_data": "4 5 6 7 0 1 2", "expected_output": "0", "is_sample": True, "order": 2},
            {"input_data": "11 13 15 17", "expected_output": "11", "is_sample": False, "order": 3},
            {"input_data": "2 1", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "5 1 2 3 4", "expected_output": "1", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 2. STRINGS (8 Questions)
    # =========================================================================
    {
        "title": "Palindrome String Validator",
        "slug": "palindrome-string-validator",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.\nGiven a string `s`, return `true` if it is a palindrome, or `false` otherwise.",
        "input_format": "A single line containing the string `s`.",
        "output_format": "Print `true` or `false`.",
        "constraints": "1 <= s.length <= 2 * 10^5\n`s` consists only of printable ASCII characters.",
        "sample_input": "A man, a plan, a canal: Panama",
        "sample_output": "true",
        "explanation": "\"amanaplanacanalpanama\" is a palindrome.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "A man, a plan, a canal: Panama", "expected_output": "true", "is_sample": True, "order": 1},
            {"input_data": "race a car", "expected_output": "false", "is_sample": True, "order": 2},
            {"input_data": " ", "expected_output": "true", "is_sample": False, "order": 3},
            {"input_data": "0P", "expected_output": "false", "is_sample": False, "order": 4},
            {"input_data": "Was it a car or a cat I saw?", "expected_output": "true", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Reverse Words in a String",
        "slug": "reverse-words-in-a-string",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Given an input string `s`, reverse the order of the words.\nA word is defined as a sequence of non-space characters. The words in `s` will be separated by at least one space.\nReturn a string of the words in reverse order concatenated by a single space.",
        "input_format": "A single line containing the string `s`.",
        "output_format": "The reversed words joined by a single space.",
        "constraints": "1 <= s.length <= 10^4\n`s` contains English letters, digits, and spaces.",
        "sample_input": "the sky is blue",
        "sample_output": "blue is sky the",
        "explanation": "Words reversed in order: blue is sky the.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "the sky is blue", "expected_output": "blue is sky the", "is_sample": True, "order": 1},
            {"input_data": "  hello world  ", "expected_output": "world hello", "is_sample": True, "order": 2},
            {"input_data": "a good   example", "expected_output": "example good a", "is_sample": False, "order": 3},
            {"input_data": "single", "expected_output": "single", "is_sample": False, "order": 4},
            {"input_data": "  EPIC   WIN  ", "expected_output": "WIN EPIC", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Valid Anagram Check",
        "slug": "valid-anagram-check",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Given two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.\nAn Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.",
        "input_format": "First line contains string `s`.\nSecond line contains string `t`.",
        "output_format": "Print `true` or `false`.",
        "constraints": "1 <= s.length, t.length <= 5 * 10^4\n`s` and `t` consist of lowercase English letters.",
        "sample_input": "anagram\nnagaram",
        "sample_output": "true",
        "explanation": "\"nagaram\" is an exact anagram of \"anagram\".",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "anagram\nnagaram", "expected_output": "true", "is_sample": True, "order": 1},
            {"input_data": "rat\ncar", "expected_output": "false", "is_sample": True, "order": 2},
            {"input_data": "listen\nsilent", "expected_output": "true", "is_sample": False, "order": 3},
            {"input_data": "a\nab", "expected_output": "false", "is_sample": False, "order": 4},
            {"input_data": "cinema\niceman", "expected_output": "true", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Longest Common Prefix",
        "slug": "longest-common-prefix",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Write a function to find the longest common prefix string amongst an array of strings.\nIf there is no common prefix, return an empty string (or empty line).",
        "input_format": "A single line containing space-separated strings.",
        "output_format": "Print the longest common prefix string.",
        "constraints": "1 <= strs.length <= 200\n0 <= strs[i].length <= 200\n`strs[i]` consists of only lowercase English letters.",
        "sample_input": "flower flow flight",
        "sample_output": "fl",
        "explanation": "\"fl\" is the longest prefix common to flower, flow, and flight.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "flower flow flight", "expected_output": "fl", "is_sample": True, "order": 1},
            {"input_data": "dog racecar car", "expected_output": "", "is_sample": True, "order": 2},
            {"input_data": "interspecies interstellar interstate", "expected_output": "inters", "is_sample": False, "order": 3},
            {"input_data": "throne throne", "expected_output": "throne", "is_sample": False, "order": 4},
            {"input_data": "ab a", "expected_output": "a", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "String to Integer (atoi)",
        "slug": "string-to-integer-atoi",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Implement the `myAtoi(string s)` function, which converts a string to a 32-bit signed integer.\n1. Read in and ignore any leading whitespace.\n2. Check if the next character is '-' or '+'.\n3. Read in next the characters until the next non-digit character or the end of the input.\n4. Clamp the integer within the 32-bit signed integer range: [-2^31, 2^31 - 1].",
        "input_format": "A single line containing string `s`.",
        "output_format": "Print the parsed 32-bit integer.",
        "constraints": "0 <= s.length <= 200\n`s` consists of English letters, digits, ' ', '+', '-', and '.'.",
        "sample_input": "42",
        "sample_output": "42",
        "explanation": "\"42\" parses directly to integer 42.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "42", "expected_output": "42", "is_sample": True, "order": 1},
            {"input_data": "   -42", "expected_output": "-42", "is_sample": True, "order": 2},
            {"input_data": "4193 with words", "expected_output": "4193", "is_sample": False, "order": 3},
            {"input_data": "words and 987", "expected_output": "0", "is_sample": False, "order": 4},
            {"input_data": "-91283472332", "expected_output": "-2147483648", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Group Anagrams by Frequency",
        "slug": "group-anagrams-by-frequency",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Given an array of strings `strs`, group the anagrams together.\nOutput each group on a new line with words sorted lexicographically, and lines sorted by the first word.",
        "input_format": "A single line containing space-separated strings.",
        "output_format": "Space-separated words grouped by anagram on separate lines or joined by comma.",
        "constraints": "1 <= strs.length <= 10^4\n0 <= strs[i].length <= 100\n`strs[i]` consists of lowercase English letters.",
        "sample_input": "eat tea tan ate nat bat",
        "sample_output": "ate,eat,tea bat nat,tan",
        "explanation": "Anagram groups are ['ate', 'eat', 'tea'], ['bat'], and ['nat', 'tan'].",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "eat tea tan ate nat bat", "expected_output": "ate,eat,tea bat nat,tan", "is_sample": True, "order": 1},
            {"input_data": "a", "expected_output": "a", "is_sample": True, "order": 2},
            {"input_data": "cat dog act god tac", "expected_output": "act,cat,tac dog,god", "is_sample": False, "order": 3},
            {"input_data": "ab ba abc cba", "expected_output": "ab,ba abc,cba", "is_sample": False, "order": 4},
            {"input_data": "hello olleh world", "expected_output": "hello,olleh world", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Count and Say Sequence",
        "slug": "count-and-say-sequence",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "The count-and-say sequence is a sequence of digit strings defined by the recursive formula:\n`countAndSay(1) = '1'`\n`countAndSay(n)` is the run-length encoding of `countAndSay(n - 1)`.\nGiven a positive integer `n`, return the `n`-th term of the count-and-say sequence.",
        "input_format": "A single integer `n`.",
        "output_format": "Print the string corresponding to the `n`-th sequence.",
        "constraints": "1 <= n <= 30",
        "sample_input": "4",
        "sample_output": "1211",
        "explanation": "countAndSay(1) = '1'\ncountAndSay(2) = '11'\ncountAndSay(3) = '21'\ncountAndSay(4) = '1211'",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "4", "expected_output": "1211", "is_sample": True, "order": 1},
            {"input_data": "1", "expected_output": "1", "is_sample": True, "order": 2},
            {"input_data": "5", "expected_output": "111221", "is_sample": False, "order": 3},
            {"input_data": "2", "expected_output": "11", "is_sample": False, "order": 4},
            {"input_data": "6", "expected_output": "312211", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Longest Palindromic Substring",
        "slug": "longest-palindromic-substring",
        "category": CodingQuestion.Categories.STRINGS,
        "description": "Given a string `s`, return the longest palindromic substring in `s`.\nIf multiple valid palindromic substrings exist of the same maximum length, return the first one.",
        "input_format": "A single line containing string `s`.",
        "output_format": "Print the longest palindromic substring.",
        "constraints": "1 <= s.length <= 1000\n`s` consist of only digits and English letters.",
        "sample_input": "babad",
        "sample_output": "bab",
        "explanation": "\"bab\" (or \"aba\") is a valid answer.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "babad", "expected_output": "bab", "is_sample": True, "order": 1},
            {"input_data": "cbbd", "expected_output": "bb", "is_sample": True, "order": 2},
            {"input_data": "a", "expected_output": "a", "is_sample": False, "order": 3},
            {"input_data": "racecar", "expected_output": "racecar", "is_sample": False, "order": 4},
            {"input_data": "forgeeksskeegfor", "expected_output": "geeksskeeg", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 3. HASHING (5 Questions)
    # =========================================================================
    {
        "title": "First Unique Character in a String",
        "slug": "first-unique-character-string",
        "category": CodingQuestion.Categories.HASHING,
        "description": "Given a string `s`, find the first non-repeating character in it and return its index. If it does not exist, return -1.",
        "input_format": "A single line containing the string `s`.",
        "output_format": "Print the 0-based index or -1.",
        "constraints": "1 <= s.length <= 10^5\n`s` consists of only lowercase English letters.",
        "sample_input": "leetcode",
        "sample_output": "0",
        "explanation": "The character 'l' at index 0 is the first character that does not occur at any other index.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "leetcode", "expected_output": "0", "is_sample": True, "order": 1},
            {"input_data": "loveleetcode", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "aabb", "expected_output": "-1", "is_sample": False, "order": 3},
            {"input_data": "z", "expected_output": "0", "is_sample": False, "order": 4},
            {"input_data": "aadada", "expected_output": "-1", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Intersection of Two Arrays",
        "slug": "intersection-of-two-arrays",
        "category": CodingQuestion.Categories.HASHING,
        "description": "Given two integer arrays `nums1` and `nums2`, return an array of their intersection.\nEach element in the result must be unique and you may return the result in sorted ascending order.",
        "input_format": "First line contains space-separated integers for `nums1`.\nSecond line contains space-separated integers for `nums2`.",
        "output_format": "Space-separated unique integers in ascending order.",
        "constraints": "1 <= nums1.length, nums2.length <= 1000\n0 <= nums1[i], nums2[i] <= 1000",
        "sample_input": "1 2 2 1\n2 2",
        "sample_output": "2",
        "explanation": "The common element is 2.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 2 1\n2 2", "expected_output": "2", "is_sample": True, "order": 1},
            {"input_data": "4 9 5\n9 4 9 8 4", "expected_output": "4 9", "is_sample": True, "order": 2},
            {"input_data": "1 3 5\n2 4 6", "expected_output": "", "is_sample": False, "order": 3},
            {"input_data": "7 7 7\n7 7", "expected_output": "7", "is_sample": False, "order": 4},
            {"input_data": "10 5 8 20\n20 10 30", "expected_output": "10 20", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Subarray Sum Equals K",
        "slug": "subarray-sum-equals-k",
        "category": CodingQuestion.Categories.HASHING,
        "description": "Given an array of integers `nums` and an integer `k`, return the total number of continuous subarrays whose sum equals to `k`.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `k`.",
        "output_format": "Print the number of matching subarrays.",
        "constraints": "1 <= nums.length <= 2 * 10^4\n-1000 <= nums[i] <= 1000\n-10^7 <= k <= 10^7",
        "sample_input": "1 1 1\n2",
        "sample_output": "2",
        "explanation": "Subarrays [1, 1] at indices [0, 1] and [1, 2] both sum to 2.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 1 1\n2", "expected_output": "2", "is_sample": True, "order": 1},
            {"input_data": "1 2 3\n3", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "1 -1 0\n0", "expected_output": "3", "is_sample": False, "order": 3},
            {"input_data": "3 4 7 2 -3 1 4 2\n7", "expected_output": "4", "is_sample": False, "order": 4},
            {"input_data": "1\n0", "expected_output": "0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Longest Consecutive Sequence",
        "slug": "longest-consecutive-sequence",
        "category": CodingQuestion.Categories.HASHING,
        "description": "Given an unsorted array of integers `nums`, return the length of the longest consecutive elements sequence.\nYou must write an algorithm that runs in O(n) time.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Print the maximum consecutive sequence length.",
        "constraints": "0 <= nums.length <= 10^5\n-10^9 <= nums[i] <= 10^9",
        "sample_input": "100 4 200 1 3 2",
        "sample_output": "4",
        "explanation": "The longest consecutive elements sequence is [1, 2, 3, 4]. Its length is 4.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "100 4 200 1 3 2", "expected_output": "4", "is_sample": True, "order": 1},
            {"input_data": "0 3 7 2 5 8 4 6 0 1", "expected_output": "9", "is_sample": True, "order": 2},
            {"input_data": "1 2 0 1", "expected_output": "3", "is_sample": False, "order": 3},
            {"input_data": "10", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "9 1 4 7 3 -1 0 5 8 -1 6", "expected_output": "7", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Isomorphic Strings Check",
        "slug": "isomorphic-strings-check",
        "category": CodingQuestion.Categories.HASHING,
        "description": "Given two strings `s` and `t`, determine if they are isomorphic.\nTwo strings `s` and `t` are isomorphic if the characters in `s` can be replaced to get `t`.",
        "input_format": "First line contains string `s`.\nSecond line contains string `t`.",
        "output_format": "Print `true` or `false`.",
        "constraints": "1 <= s.length <= 5 * 10^4\nt.length == s.length\n`s` and `t` consist of any valid ASCII character.",
        "sample_input": "egg\nadd",
        "sample_output": "true",
        "explanation": "'e' maps to 'a' and 'g' maps to 'd'.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "egg\nadd", "expected_output": "true", "is_sample": True, "order": 1},
            {"input_data": "foo\nbar", "expected_output": "false", "is_sample": True, "order": 2},
            {"input_data": "paper\ntitle", "expected_output": "true", "is_sample": False, "order": 3},
            {"input_data": "badc\nbaba", "expected_output": "false", "is_sample": False, "order": 4},
            {"input_data": "ab\naa", "expected_output": "false", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 4. TWO POINTERS / SLIDING WINDOW (5 Questions)
    # =========================================================================
    {
        "title": "Target Pair Sum",
        "slug": "target-pair-sum",
        "category": CodingQuestion.Categories.TWO_POINTERS,
        "description": "Given an array of integers `nums` and an integer `target`, return the indices of the two numbers such that they add up to `target` as a space-separated pair in ascending order (0-indexed).\nYou may assume that each input will have exactly one solution, and you may not use the same element twice.",
        "input_format": "The first line contains space-separated integers representing `nums`.\nThe second line contains a single integer `target`.",
        "output_format": "Print the two 0-indexed positions space-separated (e.g. `0 1`).",
        "constraints": "2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9\nOnly one valid answer exists.",
        "sample_input": "2 7 11 15\n9",
        "sample_output": "0 1",
        "explanation": "Because nums[0] + nums[1] == 2 + 7 == 9, we return 0 1.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "2 7 11 15\n9", "expected_output": "0 1", "is_sample": True, "order": 1},
            {"input_data": "3 2 4\n6", "expected_output": "1 2", "is_sample": True, "order": 2},
            {"input_data": "3 3\n6", "expected_output": "0 1", "is_sample": False, "order": 3},
            {"input_data": "1 5 8 12 19\n20", "expected_output": "0 4", "is_sample": False, "order": 4},
            {"input_data": "-3 4 3 90\n0", "expected_output": "0 2", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Longest Non-Repeating Substring",
        "slug": "longest-non-repeating-substring",
        "category": CodingQuestion.Categories.TWO_POINTERS,
        "description": "Given a string `s`, find the length of the longest substring without repeating characters.",
        "input_format": "A single line containing the string `s`.",
        "output_format": "A single integer denoting the length.",
        "constraints": "0 <= s.length <= 5 * 10^4\n`s` consists of English letters, digits, symbols and spaces.",
        "sample_input": "abcabcbb",
        "sample_output": "3",
        "explanation": "The answer is \"abc\", with the length of 3.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "abcabcbb", "expected_output": "3", "is_sample": True, "order": 1},
            {"input_data": "bbbbb", "expected_output": "1", "is_sample": True, "order": 2},
            {"input_data": "pwwkew", "expected_output": "3", "is_sample": False, "order": 3},
            {"input_data": " ", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "dvdf", "expected_output": "3", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "3Sum Zero Triplet Search",
        "slug": "3sum-zero-triplet-search",
        "category": CodingQuestion.Categories.TWO_POINTERS,
        "description": "Given an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`.\nNotice that the solution set must not contain duplicate triplets. Print each triplet on a line in sorted order.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Space-separated triplets in ascending order separated by semicolons or commas.",
        "constraints": "3 <= nums.length <= 3000\n-10^5 <= nums[i] <= 10^5",
        "sample_input": "-1 0 1 2 -1 -4",
        "sample_output": "-1 -1 2, -1 0 1",
        "explanation": "The distinct triplets are [-1, 0, 1] and [-1, -1, 2].",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "-1 0 1 2 -1 -4", "expected_output": "-1 -1 2, -1 0 1", "is_sample": True, "order": 1},
            {"input_data": "0 1 1", "expected_output": "", "is_sample": True, "order": 2},
            {"input_data": "0 0 0", "expected_output": "0 0 0", "is_sample": False, "order": 3},
            {"input_data": "-2 0 1 1 2", "expected_output": "-2 0 2, -2 1 1", "is_sample": False, "order": 4},
            {"input_data": "-4 -2 -2 -2 0 1 2 2 2 3 3 4 4 6 6", "expected_output": "-4 -2 6, -4 0 4, -4 1 3, -4 2 2, -2 -2 4, -2 0 2", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Trapping Rain Water",
        "slug": "trapping-rain-water",
        "category": CodingQuestion.Categories.TWO_POINTERS,
        "description": "Given `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.",
        "input_format": "A single line containing space-separated integers for `height`.",
        "output_format": "Print the total trapped water volume as an integer.",
        "constraints": "n == height.length\n1 <= n <= 2 * 10^4\n0 <= height[i] <= 10^5",
        "sample_input": "0 1 0 2 1 0 1 3 2 1 2 1",
        "sample_output": "6",
        "explanation": "The elevation map traps 6 units of rain water.",
        "difficulty": "HARD",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "0 1 0 2 1 0 1 3 2 1 2 1", "expected_output": "6", "is_sample": True, "order": 1},
            {"input_data": "4 2 0 3 2 5", "expected_output": "9", "is_sample": True, "order": 2},
            {"input_data": "3 0 2 0 4", "expected_output": "7", "is_sample": False, "order": 3},
            {"input_data": "1 2 3 4 5", "expected_output": "0", "is_sample": False, "order": 4},
            {"input_data": "5 4 1 2", "expected_output": "1", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Minimum Window Substring",
        "slug": "minimum-window-substring",
        "category": CodingQuestion.Categories.TWO_POINTERS,
        "description": "Given two strings `s` and `t` of lengths `m` and `n` respectively, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included in the window.\nIf there is no such substring, return the empty string \"\".",
        "input_format": "First line contains string `s`.\nSecond line contains string `t`.",
        "output_format": "Print the minimum window substring.",
        "constraints": "m == s.length, n == t.length\n1 <= m, n <= 10^5\n`s` and `t` consist of uppercase and lowercase English letters.",
        "sample_input": "ADOBECODEBANC\nABC",
        "sample_output": "BANC",
        "explanation": "The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t.",
        "difficulty": "HARD",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "ADOBECODEBANC\nABC", "expected_output": "BANC", "is_sample": True, "order": 1},
            {"input_data": "a\na", "expected_output": "a", "is_sample": True, "order": 2},
            {"input_data": "a\naa", "expected_output": "", "is_sample": False, "order": 3},
            {"input_data": "ab\nb", "expected_output": "b", "is_sample": False, "order": 4},
            {"input_data": "cabwefgewcwaefgcf\ncae", "expected_output": "cwae", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 5. SEARCHING / SORTING (5 Questions)
    # =========================================================================
    {
        "title": "Binary Search in Sorted Array",
        "slug": "binary-search-sorted-array",
        "category": CodingQuestion.Categories.SEARCH_SORT,
        "description": "Given an array of integers `nums` which is sorted in ascending order, and an integer `target`, write a function to search `target` in `nums`. If `target` exists, then return its index. Otherwise, return -1.\nYou must write an algorithm with O(log n) runtime complexity.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `target`.",
        "output_format": "Print the 0-based target index or -1.",
        "constraints": "1 <= nums.length <= 10^4\n-10^4 < nums[i], target < 10^4\nAll the integers in `nums` are unique.\n`nums` is sorted in ascending order.",
        "sample_input": "-1 0 3 5 9 12\n9",
        "sample_output": "4",
        "explanation": "9 exists in nums and its index is 4.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "-1 0 3 5 9 12\n9", "expected_output": "4", "is_sample": True, "order": 1},
            {"input_data": "-1 0 3 5 9 12\n2", "expected_output": "-1", "is_sample": True, "order": 2},
            {"input_data": "5\n5", "expected_output": "0", "is_sample": False, "order": 3},
            {"input_data": "2 5\n5", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "1 3 5 7 9 11\n1", "expected_output": "0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Search in Rotated Sorted Array",
        "slug": "search-in-rotated-sorted-array",
        "category": CodingQuestion.Categories.SEARCH_SORT,
        "description": "There is an integer array `nums` sorted in ascending order with distinct values.\nGiven the array `nums` after possible rotation and an integer `target`, return the index of `target` if it is in `nums`, or -1 if it is not in `nums`.\nYou must write an algorithm with O(log n) runtime complexity.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `target`.",
        "output_format": "Print index or -1.",
        "constraints": "1 <= nums.length <= 5000\n-10^4 <= nums[i] <= 10^4\nAll values of `nums` are unique.",
        "sample_input": "4 5 6 7 0 1 2\n0",
        "sample_output": "4",
        "explanation": "0 is at index 4.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "4 5 6 7 0 1 2\n0", "expected_output": "4", "is_sample": True, "order": 1},
            {"input_data": "4 5 6 7 0 1 2\n3", "expected_output": "-1", "is_sample": True, "order": 2},
            {"input_data": "1\n0", "expected_output": "-1", "is_sample": False, "order": 3},
            {"input_data": "3 1\n1", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "5 1 3\n5", "expected_output": "0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Find First and Last Position in Sorted Array",
        "slug": "find-first-last-position-sorted-array",
        "category": CodingQuestion.Categories.SEARCH_SORT,
        "description": "Given an array of integers `nums` sorted in non-decreasing order, find the starting and ending position of a given `target` value.\nIf `target` is not found in the array, return `[-1, -1]`.\nYou must write an algorithm with O(log n) runtime complexity.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `target`.",
        "output_format": "Print two space-separated integers: `start_index end_index`.",
        "constraints": "0 <= nums.length <= 10^5\n-10^9 <= nums[i] <= 10^9\n`nums` is a non-decreasing array.\n-10^9 <= target <= 10^9",
        "sample_input": "5 7 7 8 8 10\n8",
        "sample_output": "3 4",
        "explanation": "8 appears starting at index 3 and ending at index 4.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "5 7 7 8 8 10\n8", "expected_output": "3 4", "is_sample": True, "order": 1},
            {"input_data": "5 7 7 8 8 10\n6", "expected_output": "-1 -1", "is_sample": True, "order": 2},
            {"input_data": "\n0", "expected_output": "-1 -1", "is_sample": False, "order": 3},
            {"input_data": "1\n1", "expected_output": "0 0", "is_sample": False, "order": 4},
            {"input_data": "2 2 2 2 2\n2", "expected_output": "0 4", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Kth Largest Element in an Array",
        "slug": "kth-largest-element-array",
        "category": CodingQuestion.Categories.SEARCH_SORT,
        "description": "Given an integer array `nums` and an integer `k`, return the `k`-th largest element in the array.\nNote that it is the `k`-th largest element in the sorted order, not the `k`-th distinct element.",
        "input_format": "First line contains space-separated integers for `nums`.\nSecond line contains integer `k`.",
        "output_format": "Print the `k`-th largest integer.",
        "constraints": "1 <= k <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4",
        "sample_input": "3 2 1 5 6 4\n2",
        "sample_output": "5",
        "explanation": "Sorted in descending order: 6, 5, 4, 3, 2, 1. The 2nd largest element is 5.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 2 1 5 6 4\n2", "expected_output": "5", "is_sample": True, "order": 1},
            {"input_data": "3 2 3 1 2 4 5 5 6\n4", "expected_output": "4", "is_sample": True, "order": 2},
            {"input_data": "1\n1", "expected_output": "1", "is_sample": False, "order": 3},
            {"input_data": "7 10 4 3 20 15\n3", "expected_output": "10", "is_sample": False, "order": 4},
            {"input_data": "-1 2 0\n1", "expected_output": "2", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Median of Two Sorted Arrays",
        "slug": "median-of-two-sorted-arrays",
        "category": CodingQuestion.Categories.SEARCH_SORT,
        "description": "Given two sorted arrays `nums1` and `nums2` of size `m` and `n` respectively, return the median of the two sorted arrays.\nThe overall run time complexity should be O(log (m+n)).",
        "input_format": "First line contains space-separated integers for `nums1`.\nSecond line contains space-separated integers for `nums2`.",
        "output_format": "Print the median as a float formatted to at least 1 decimal place (e.g. 2.0 or 2.5).",
        "constraints": "nums1.length == m, nums2.length == n\n0 <= m <= 1000, 0 <= n <= 1000\n1 <= m + n <= 2000\n-10^6 <= nums1[i], nums2[i] <= 10^6",
        "sample_input": "1 3\n2",
        "sample_output": "2.0",
        "explanation": "merged array = [1,2,3] and median is 2.0.",
        "difficulty": "HARD",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 3\n2", "expected_output": "2.0", "is_sample": True, "order": 1},
            {"input_data": "1 2\n3 4", "expected_output": "2.5", "is_sample": True, "order": 2},
            {"input_data": "0 0\n0 0", "expected_output": "0.0", "is_sample": False, "order": 3},
            {"input_data": "\n1", "expected_output": "1.0", "is_sample": False, "order": 4},
            {"input_data": "2\n", "expected_output": "2.0", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 6. STACK / QUEUE (5 Questions)
    # =========================================================================
    {
        "title": "Valid Parentheses String",
        "slug": "valid-parentheses-string",
        "category": CodingQuestion.Categories.STACK_QUEUE,
        "description": "Given a string `s` containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.",
        "input_format": "A single line containing the brackets string `s`.",
        "output_format": "Print `true` if valid, `false` otherwise.",
        "constraints": "1 <= s.length <= 10^4\n`s` consists of parentheses only '()[]{}'.",
        "sample_input": "()[]{}",
        "sample_output": "true",
        "explanation": "All brackets open and close properly in order.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "()[]{}", "expected_output": "true", "is_sample": True, "order": 1},
            {"input_data": "(]", "expected_output": "false", "is_sample": True, "order": 2},
            {"input_data": "([{}])", "expected_output": "true", "is_sample": False, "order": 3},
            {"input_data": "[(])", "expected_output": "false", "is_sample": False, "order": 4},
            {"input_data": "{[]}", "expected_output": "true", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Min Stack Implementation",
        "slug": "min-stack-operations",
        "category": CodingQuestion.Categories.STACK_QUEUE,
        "description": "Simulate a stack that supports push, pop, top, and retrieving the minimum element in constant time.\nInput is a sequence of operations:\n- `push X`\n- `pop`\n- `top`\n- `getMin`\nPrint results of `top` and `getMin` operations separated by space.",
        "input_format": "Lines of stack operations.",
        "output_format": "Space-separated outputs from top and getMin queries.",
        "constraints": "-2^31 <= val <= 2^31 - 1\nOperations count <= 3 * 10^4",
        "sample_input": "push -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin",
        "sample_output": "-3 0 -2",
        "explanation": "getMin returns -3. After pop, top is 0 and getMin is -2.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "push -2\npush 0\npush -3\ngetMin\npop\ntop\ngetMin", "expected_output": "-3 0 -2", "is_sample": True, "order": 1},
            {"input_data": "push 1\npush 2\ntop\ngetMin", "expected_output": "2 1", "is_sample": True, "order": 2},
            {"input_data": "push 5\ngetMin\npush 3\ngetMin\npop\ngetMin", "expected_output": "5 3 5", "is_sample": False, "order": 3},
            {"input_data": "push 0\npush 1\npush 0\ngetMin\npop\ngetMin", "expected_output": "0 0", "is_sample": False, "order": 4},
            {"input_data": "push 10\ntop\ngetMin", "expected_output": "10 10", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Daily Temperatures Waiting Time",
        "slug": "daily-temperatures-waiting-time",
        "category": CodingQuestion.Categories.STACK_QUEUE,
        "description": "Given an array of integers `temperatures` represents the daily temperatures, return an array `answer` such that `answer[i]` is the number of days you have to wait after the `i`-th day to get a warmer temperature.\nIf there is no future day for which this is possible, keep `answer[i] == 0` instead.",
        "input_format": "A single line containing space-separated integers.",
        "output_format": "Space-separated integers representing days to wait.",
        "constraints": "1 <= temperatures.length <= 10^5\n30 <= temperatures[i] <= 100",
        "sample_input": "73 74 75 71 69 72 76 73",
        "sample_output": "1 1 4 2 1 1 0 0",
        "explanation": "Day 0 (73) has warmer day at Day 1 (74), wait = 1. Day 2 (75) has warmer day at Day 6 (76), wait = 4.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "73 74 75 71 69 72 76 73", "expected_output": "1 1 4 2 1 1 0 0", "is_sample": True, "order": 1},
            {"input_data": "30 40 50 60", "expected_output": "1 1 1 0", "is_sample": True, "order": 2},
            {"input_data": "30 60 90", "expected_output": "1 1 0", "is_sample": False, "order": 3},
            {"input_data": "89 62 70 58 47 47 46 76 100 70", "expected_output": "8 1 5 4 3 2 1 1 0 0", "is_sample": False, "order": 4},
            {"input_data": "50 50 50", "expected_output": "0 0 0", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Evaluate Reverse Polish Notation",
        "slug": "evaluate-reverse-polish-notation",
        "category": CodingQuestion.Categories.STACK_QUEUE,
        "description": "You are given an array of strings `tokens` that represents an arithmetic expression in a Reverse Polish Notation.\nEvaluate the expression. Return an integer that represents the value of the expression.\nValid operators are '+', '-', '*', and '/'. Division truncates toward zero.",
        "input_format": "A single line containing space-separated tokens.",
        "output_format": "Print the evaluated integer result.",
        "constraints": "1 <= tokens.length <= 10^4\n`tokens[i]` is either an operator: '+', '-', '*', or '/', or an integer in the range [-200, 200].",
        "sample_input": "2 1 + 3 *",
        "sample_output": "9",
        "explanation": "((2 + 1) * 3) = 9",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "2 1 + 3 *", "expected_output": "9", "is_sample": True, "order": 1},
            {"input_data": "4 13 5 / +", "expected_output": "6", "is_sample": True, "order": 2},
            {"input_data": "10 6 9 3 + -11 * / * 17 + 5 +", "expected_output": "22", "is_sample": False, "order": 3},
            {"input_data": "3 4 -", "expected_output": "-1", "is_sample": False, "order": 4},
            {"input_data": "18", "expected_output": "18", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Largest Rectangle in Histogram",
        "slug": "largest-rectangle-histogram",
        "category": CodingQuestion.Categories.STACK_QUEUE,
        "description": "Given an array of integers `heights` representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Print the maximum rectangle area as an integer.",
        "constraints": "1 <= heights.length <= 10^5\n0 <= heights[i] <= 10^4",
        "sample_input": "2 1 5 6 2 3",
        "sample_output": "10",
        "explanation": "The maximum area is 10 units between heights 5 and 6: min(5,6)*2 = 10.",
        "difficulty": "HARD",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "2 1 5 6 2 3", "expected_output": "10", "is_sample": True, "order": 1},
            {"input_data": "2 4", "expected_output": "4", "is_sample": True, "order": 2},
            {"input_data": "1", "expected_output": "1", "is_sample": False, "order": 3},
            {"input_data": "6 7 5 2 4 5 9 3", "expected_output": "16", "is_sample": False, "order": 4},
            {"input_data": "2 1 2", "expected_output": "3", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 7. LINKED LIST (4 Questions)
    # =========================================================================
    {
        "title": "Reverse a Singly Linked List",
        "slug": "reverse-singly-linked-list",
        "category": CodingQuestion.Categories.LINKED_LIST,
        "description": "Given the head of a singly linked list represented as space-separated values, reverse the list, and return the reversed list values.",
        "input_format": "A single line of space-separated integers.",
        "output_format": "Space-separated integers representing the reversed list.",
        "constraints": "The number of nodes in the list is the range [0, 5000].\n-5000 <= Node.val <= 5000",
        "sample_input": "1 2 3 4 5",
        "sample_output": "5 4 3 2 1",
        "explanation": "Reversed order: 5 4 3 2 1.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 3 4 5", "expected_output": "5 4 3 2 1", "is_sample": True, "order": 1},
            {"input_data": "1 2", "expected_output": "2 1", "is_sample": True, "order": 2},
            {"input_data": "10", "expected_output": "10", "is_sample": False, "order": 3},
            {"input_data": "", "expected_output": "", "is_sample": False, "order": 4},
            {"input_data": "7 8 9 10", "expected_output": "10 9 8 7", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Detect Cycle in Linked List",
        "slug": "detect-cycle-linked-list",
        "category": CodingQuestion.Categories.LINKED_LIST,
        "description": "Given a linked list and position `pos` representing the index of the node that tail's next pointer is connected to (0-indexed, or -1 if no cycle), return `true` if there is a cycle in the linked list, or `false` otherwise.",
        "input_format": "First line contains space-separated node values.\nSecond line contains integer `pos`.",
        "output_format": "Print `true` if cycle exists, `false` otherwise.",
        "constraints": "The number of the nodes in the list is in the range [0, 10^4].\n-10^5 <= Node.val <= 10^5\n`pos` is -1 or a valid index in the linked-list.",
        "sample_input": "3 2 0 -4\n1",
        "sample_output": "true",
        "explanation": "There is a cycle where tail connects to the 1st node (val 2).",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 2 0 -4\n1", "expected_output": "true", "is_sample": True, "order": 1},
            {"input_data": "1 2\n0", "expected_output": "true", "is_sample": True, "order": 2},
            {"input_data": "1\n-1", "expected_output": "false", "is_sample": False, "order": 3},
            {"input_data": "1 2 3 4 5\n-1", "expected_output": "false", "is_sample": False, "order": 4},
            {"input_data": "5 10 15\n2", "expected_output": "true", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Merge Two Sorted Lists",
        "slug": "merge-two-sorted-lists",
        "category": CodingQuestion.Categories.LINKED_LIST,
        "description": "You are given the heads of two sorted linked lists `list1` and `list2`.\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\nReturn the merged linked list values space-separated.",
        "input_format": "First line contains space-separated integers for `list1`.\nSecond line contains space-separated integers for `list2`.",
        "output_format": "Space-separated integers for merged sorted list.",
        "constraints": "The number of nodes in both lists is in the range [0, 50].\n-100 <= Node.val <= 100\nBoth `list1` and `list2` are sorted in non-decreasing order.",
        "sample_input": "1 2 4\n1 3 4",
        "sample_output": "1 1 2 3 4 4",
        "explanation": "Merged sorted sequence: 1 1 2 3 4 4.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 4\n1 3 4", "expected_output": "1 1 2 3 4 4", "is_sample": True, "order": 1},
            {"input_data": "\n0", "expected_output": "0", "is_sample": True, "order": 2},
            {"input_data": "5 10 15\n2 3 20", "expected_output": "2 3 5 10 15 20", "is_sample": False, "order": 3},
            {"input_data": "1 3 5\n2 4 6", "expected_output": "1 2 3 4 5 6", "is_sample": False, "order": 4},
            {"input_data": "10\n5", "expected_output": "5 10", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Remove Nth Node From End of List",
        "slug": "remove-nth-node-from-end",
        "category": CodingQuestion.Categories.LINKED_LIST,
        "description": "Given the head of a linked list, remove the `n`-th node from the end of the list and return its head values.",
        "input_format": "First line contains space-separated integers representing node values.\nSecond line contains integer `n`.",
        "output_format": "Space-separated integers for the remaining list.",
        "constraints": "The number of nodes in the list is `sz`.\n1 <= sz <= 30\n0 <= Node.val <= 100\n1 <= n <= sz",
        "sample_input": "1 2 3 4 5\n2",
        "sample_output": "1 2 3 5",
        "explanation": "The 2nd node from the end is 4. Removing it leaves 1 2 3 5.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 3 4 5\n2", "expected_output": "1 2 3 5", "is_sample": True, "order": 1},
            {"input_data": "1\n1", "expected_output": "", "is_sample": True, "order": 2},
            {"input_data": "1 2\n1", "expected_output": "1", "is_sample": False, "order": 3},
            {"input_data": "1 2\n2", "expected_output": "2", "is_sample": False, "order": 4},
            {"input_data": "10 20 30 40\n4", "expected_output": "20 30 40", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 8. RECURSION (3 Questions)
    # =========================================================================
    {
        "title": "Generate Parentheses Combinations",
        "slug": "generate-parentheses-combinations",
        "category": CodingQuestion.Categories.RECURSION,
        "description": "Given `n` pairs of parentheses, write a function to generate all combinations of well-formed parentheses.\nPrint all combinations separated by space in lexicographical order.",
        "input_format": "A single integer `n`.",
        "output_format": "Space-separated strings representing valid combinations.",
        "constraints": "1 <= n <= 8",
        "sample_input": "3",
        "sample_output": "((())) (()()) (())() ()(()) ()()()",
        "explanation": "5 valid well-formed parentheses combinations of length 6.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3", "expected_output": "((())) (()()) (())() ()(()) ()()()", "is_sample": True, "order": 1},
            {"input_data": "1", "expected_output": "()", "is_sample": True, "order": 2},
            {"input_data": "2", "expected_output": "(()) ()()", "is_sample": False, "order": 3},
            {"input_data": "4", "expected_output": "(((()))) ((()())) ((())()) ((())()) ((())(())) ((()))() (()(())) (()()()) (()())() (())(()) (())()() ()((())) ()(()()) ()(())() ()()(()) ()()()()", "is_sample": False, "order": 4},
            {"input_data": "0", "expected_output": "", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Subsets Power Set Generator",
        "slug": "subsets-power-set-generator",
        "category": CodingQuestion.Categories.RECURSION,
        "description": "Given an integer array `nums` of unique elements, return all possible subsets (the power set).\nThe solution set must not contain duplicate subsets. Return the count of subsets or subsets formatted as comma-separated groups.",
        "input_format": "A single line containing space-separated integers.",
        "output_format": "Print the total number of subsets and subsets separated by comma.",
        "constraints": "1 <= nums.length <= 10\n-10 <= nums[i] <= 10\nAll the numbers of `nums` are unique.",
        "sample_input": "1 2 3",
        "sample_output": "[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]",
        "explanation": "8 total subsets in the power set.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 3", "expected_output": "[],[1],[2],[1,2],[3],[1,3],[2,3],[1,2,3]", "is_sample": True, "order": 1},
            {"input_data": "0", "expected_output": "[],[0]", "is_sample": True, "order": 2},
            {"input_data": "1 2", "expected_output": "[],[1],[2],[1,2]", "is_sample": False, "order": 3},
            {"input_data": "5", "expected_output": "[],[5]", "is_sample": False, "order": 4},
            {"input_data": "9 10", "expected_output": "[],[9],[10],[9,10]", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Letter Combinations of a Phone Number",
        "slug": "letter-combinations-phone-number",
        "category": CodingQuestion.Categories.RECURSION,
        "description": "Given a string containing digits from `2-9` inclusive, return all possible letter combinations that the number could represent. Return the answer in lexicographical order space-separated.\nA mapping of digits to letters (just like on telephone buttons): 2:abc, 3:def, 4:ghi, 5:jkl, 6:mno, 7:pqrs, 8:tuv, 9:wxyz.",
        "input_format": "A single line containing digits string `digits`.",
        "output_format": "Space-separated combination strings.",
        "constraints": "0 <= digits.length <= 4\n`digits[i]` is a digit in the range ['2', '9'].",
        "sample_input": "23",
        "sample_output": "ad ae af bd be bf cd ce cf",
        "explanation": "3 * 3 = 9 possible letter combinations.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "23", "expected_output": "ad ae af bd be bf cd ce cf", "is_sample": True, "order": 1},
            {"input_data": "2", "expected_output": "a b c", "is_sample": True, "order": 2},
            {"input_data": "", "expected_output": "", "is_sample": False, "order": 3},
            {"input_data": "7", "expected_output": "p q r s", "is_sample": False, "order": 4},
            {"input_data": "99", "expected_output": "ww wx wy wz xw xx xy xz yw yx yy yz zw zx zy zz", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 9. TREES (3 Questions)
    # =========================================================================
    {
        "title": "Maximum Depth of Binary Tree",
        "slug": "maximum-depth-binary-tree",
        "category": CodingQuestion.Categories.TREES,
        "description": "Given the root of a binary tree represented as level-order space-separated values ('null' for missing nodes), return its maximum depth.\nA binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.",
        "input_format": "A single line containing level-order node values.",
        "output_format": "Print the maximum depth integer.",
        "constraints": "The number of nodes in the tree is in the range [0, 10^4].\n-100 <= Node.val <= 100",
        "sample_input": "3 9 20 null null 15 7",
        "sample_output": "3",
        "explanation": "Root 3 -> 20 -> 15 gives depth 3.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3 9 20 null null 15 7", "expected_output": "3", "is_sample": True, "order": 1},
            {"input_data": "1 null 2", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "", "expected_output": "0", "is_sample": False, "order": 3},
            {"input_data": "0", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "1 2 3 4 5", "expected_output": "3", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Invert / Flip Binary Tree",
        "slug": "invert-binary-tree",
        "category": CodingQuestion.Categories.TREES,
        "description": "Given the root of a binary tree in level-order format, invert the tree (swap left and right children recursively), and return its level-order representation.",
        "input_format": "A single line of space-separated level-order node values.",
        "output_format": "Space-separated level-order values of the inverted tree.",
        "constraints": "The number of nodes in the tree is in the range [0, 100].\n-100 <= Node.val <= 100",
        "sample_input": "4 2 7 1 3 6 9",
        "sample_output": "4 7 2 9 6 3 1",
        "explanation": "All left and right subtrees are mirrored.",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "4 2 7 1 3 6 9", "expected_output": "4 7 2 9 6 3 1", "is_sample": True, "order": 1},
            {"input_data": "2 1 3", "expected_output": "2 3 1", "is_sample": True, "order": 2},
            {"input_data": "", "expected_output": "", "is_sample": False, "order": 3},
            {"input_data": "1", "expected_output": "1", "is_sample": False, "order": 4},
            {"input_data": "1 2 null", "expected_output": "1 null 2", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Lowest Common Ancestor in Binary Search Tree",
        "slug": "lowest-common-ancestor-bst",
        "category": CodingQuestion.Categories.TREES,
        "description": "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes `p` and `q` in the BST.\nThe lowest common ancestor is defined between two nodes `p` and `q` as the lowest node in `T` that has both `p` and `q` as descendants.",
        "input_format": "First line contains level-order BST node values.\nSecond line contains two space-separated integers `p` and `q`.",
        "output_format": "Print the value of the LCA node.",
        "constraints": "The number of nodes in the tree is in the range [2, 10^5].\n-10^9 <= Node.val <= 10^9\nAll `Node.val` are unique.\n`p != q` and `p` and `q` will exist in the BST.",
        "sample_input": "6 2 8 0 4 7 9 null null 3 5\n2 8",
        "sample_output": "6",
        "explanation": "The LCA of nodes 2 and 8 is 6.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "6 2 8 0 4 7 9 null null 3 5\n2 8", "expected_output": "6", "is_sample": True, "order": 1},
            {"input_data": "6 2 8 0 4 7 9 null null 3 5\n2 4", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "2 1\n2 1", "expected_output": "2", "is_sample": False, "order": 3},
            {"input_data": "5 3 6 2 4 null null 1\n1 4", "expected_output": "3", "is_sample": False, "order": 4},
            {"input_data": "20 10 30\n10 30", "expected_output": "20", "is_sample": False, "order": 5},
        ],
    },

    # =========================================================================
    # 10. DYNAMIC PROGRAMMING (4 Questions)
    # =========================================================================
    {
        "title": "Climbing Stairs Ways",
        "slug": "climbing-stairs-ways",
        "category": CodingQuestion.Categories.DP,
        "description": "You are climbing a staircase. It takes `n` steps to reach the top.\nEach time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
        "input_format": "A single integer `n`.",
        "output_format": "Print the number of distinct ways as an integer.",
        "constraints": "1 <= n <= 45",
        "sample_input": "3",
        "sample_output": "3",
        "explanation": "There are three ways to climb to the top:\n1. 1 step + 1 step + 1 step\n2. 1 step + 2 steps\n3. 2 steps + 1 step",
        "difficulty": "EASY",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "3", "expected_output": "3", "is_sample": True, "order": 1},
            {"input_data": "2", "expected_output": "2", "is_sample": True, "order": 2},
            {"input_data": "1", "expected_output": "1", "is_sample": False, "order": 3},
            {"input_data": "4", "expected_output": "5", "is_sample": False, "order": 4},
            {"input_data": "5", "expected_output": "8", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Coin Change Minimum Coins",
        "slug": "coin-change-minimum-coins",
        "category": CodingQuestion.Categories.DP,
        "description": "You are given an integer array `coins` representing coins of different denominations and an integer `amount` representing a total amount of money.\nReturn the fewest number of coins that you need to make up that amount. If that amount of money cannot be made up by any combination of the coins, return -1.\nYou may assume that you have an infinite number of each kind of coin.",
        "input_format": "First line contains space-separated integers for `coins`.\nSecond line contains integer `amount`.",
        "output_format": "Print the minimum coin count or -1.",
        "constraints": "1 <= coins.length <= 12\n1 <= coins[i] <= 2^31 - 1\n0 <= amount <= 10^4",
        "sample_input": "1 2 5\n11",
        "sample_output": "3",
        "explanation": "11 = 5 + 5 + 1 (3 coins).",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "1 2 5\n11", "expected_output": "3", "is_sample": True, "order": 1},
            {"input_data": "2\n3", "expected_output": "-1", "is_sample": True, "order": 2},
            {"input_data": "1\n0", "expected_output": "0", "is_sample": False, "order": 3},
            {"input_data": "2 5 10 1\n27", "expected_output": "4", "is_sample": False, "order": 4},
            {"input_data": "186 419 83 408\n6249", "expected_output": "20", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "Longest Increasing Subsequence",
        "slug": "longest-increasing-subsequence",
        "category": CodingQuestion.Categories.DP,
        "description": "Given an integer array `nums`, return the length of the longest strictly increasing subsequence.\nA subsequence is a sequence that can be derived from an array by deleting some or no elements without changing the order of the remaining elements.",
        "input_format": "A single line containing space-separated integers for `nums`.",
        "output_format": "Print the length of the longest increasing subsequence.",
        "constraints": "1 <= nums.length <= 2500\n-10^4 <= nums[i] <= 10^4",
        "sample_input": "10 9 2 5 3 7 101 18",
        "sample_output": "4",
        "explanation": "The longest increasing subsequence is [2, 3, 7, 101], therefore the length is 4.",
        "difficulty": "MEDIUM",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "10 9 2 5 3 7 101 18", "expected_output": "4", "is_sample": True, "order": 1},
            {"input_data": "0 1 0 3 2 3", "expected_output": "4", "is_sample": True, "order": 2},
            {"input_data": "7 7 7 7 7", "expected_output": "1", "is_sample": False, "order": 3},
            {"input_data": "1 3 6 7 9 4 10 5 6", "expected_output": "6", "is_sample": False, "order": 4},
            {"input_data": "4 10 4 3 8 9", "expected_output": "3", "is_sample": False, "order": 5},
        ],
    },
    {
        "title": "0/1 Knapsack Value Optimization",
        "slug": "zero-one-knapsack-value-optimization",
        "category": CodingQuestion.Categories.DP,
        "description": "Given weights and values of `n` items, put these items in a knapsack of capacity `W` to get the maximum total value in the knapsack.\nEach item can either be chosen once or not chosen (0-1 property).",
        "input_format": "First line contains space-separated integers for item `values`.\nSecond line contains space-separated integers for item `weights`.\nThird line contains integer capacity `W`.",
        "output_format": "Print the maximum value integer.",
        "constraints": "1 <= n <= 1000\n1 <= W <= 1000\n1 <= values[i], weights[i] <= 1000",
        "sample_input": "60 100 120\n10 20 30\n50",
        "sample_output": "220",
        "explanation": "Take item 2 (w=20, v=100) and item 3 (w=30, v=120) for total weight 50 and maximum value 220.",
        "difficulty": "HARD",
        "max_score": 100,
        "starter_code": EMPTY_STARTER_CODE,
        "test_cases": [
            {"input_data": "60 100 120\n10 20 30\n50", "expected_output": "220", "is_sample": True, "order": 1},
            {"input_data": "10 20 30\n1 1 1\n2", "expected_output": "50", "is_sample": True, "order": 2},
            {"input_data": "20 5 10 40 15 25\n1 2 3 8 7 4\n10", "expected_output": "60", "is_sample": False, "order": 3},
            {"input_data": "10\n5\n4", "expected_output": "0", "is_sample": False, "order": 4},
            {"input_data": "15 20 50\n1 2 3\n5", "expected_output": "70", "is_sample": False, "order": 5},
        ],
    },
]


def ensure_coding_bank_seeded() -> int:
    """Seed the CodingQuestion bank and test cases idempotently."""
    created_count = 0
    for q_data in DEFAULT_CODING_QUESTIONS:
        tcs_data = q_data.get("test_cases", [])
        starter = q_data.get("starter_code", EMPTY_STARTER_CODE)

        question, created = CodingQuestion.objects.update_or_create(
            slug=q_data["slug"],
            defaults={
                "title": q_data["title"],
                "category": q_data.get("category", CodingQuestion.Categories.ARRAYS),
                "description": q_data["description"],
                "input_format": q_data["input_format"],
                "output_format": q_data["output_format"],
                "constraints": q_data.get("constraints", ""),
                "sample_input": q_data["sample_input"],
                "sample_output": q_data["sample_output"],
                "explanation": q_data.get("explanation", ""),
                "difficulty": q_data.get("difficulty", "MEDIUM"),
                "max_score": q_data.get("max_score", 100),
                "starter_code": starter,
            },
        )
        if created:
            created_count += 1

        # Seed test cases
        existing_orders = set()
        for tc_dict in tcs_data:
            order = tc_dict.get("order", 1)
            existing_orders.add(order)
            CodingTestCase.objects.update_or_create(
                question=question,
                order=order,
                defaults={
                    "input_data": tc_dict["input_data"],
                    "expected_output": tc_dict["expected_output"],
                    "is_sample": tc_dict.get("is_sample", False),
                },
            )

        # Clean up any extraneous test cases not in specification
        question.test_cases.exclude(order__in=existing_orders).delete()

    return created_count