# Generated by Django 6.1 on 2026-08-24 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('ADMIN_LOGIN', 'Admin Login'), ('QUESTION_CREATED', 'Question Created'), ('QUESTION_UPDATED', 'Question Updated'), ('QUESTION_STATUS_TOGGLED', 'Question Status Toggled'), ('QUESTION_DELETED', 'Question Deleted'), ('BULK_QUESTION_ACTION', 'Bulk Question Action'), ('EMPLOYER_STATUS_CHANGED', 'Employer Status Changed'), ('CANDIDATE_VIEWED', 'Candidate Viewed'), ('ASSESSMENT_VIEWED', 'Assessment Viewed'), ('REPORT_GENERATED', 'Report Generated')], db_index=True, max_length=50)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type', 'created_at'], name='dashboard_a_action__01a1f5_idx')],
            },
        ),
    ]
